// Generated by gencpp from file usv_msgs/GlbObsRcvRequest.msg
// DO NOT EDIT!


#ifndef USV_MSGS_MESSAGE_GLBOBSRCVREQUEST_H
#define USV_MSGS_MESSAGE_GLBOBSRCVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_msgs
{
template <class ContainerAllocator>
struct GlbObsRcvRequest_
{
  typedef GlbObsRcvRequest_<ContainerAllocator> Type;

  GlbObsRcvRequest_()
    : req(false)  {
    }
  GlbObsRcvRequest_(const ContainerAllocator& _alloc)
    : req(false)  {
  (void)_alloc;
    }



   typedef uint8_t _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GlbObsRcvRequest_

typedef ::usv_msgs::GlbObsRcvRequest_<std::allocator<void> > GlbObsRcvRequest;

typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvRequest > GlbObsRcvRequestPtr;
typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvRequest const> GlbObsRcvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator1> & lhs, const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req == rhs.req;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator1> & lhs, const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be3c44e19d0c6b00b25e356c69155e2a";
  }

  static const char* value(const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe3c44e19d0c6b00ULL;
  static const uint64_t static_value2 = 0xb25e356c69155e2aULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msgs/GlbObsRcvRequest";
  }

  static const char* value(const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool req\n"
;
  }

  static const char* value(const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlbObsRcvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msgs::GlbObsRcvRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSGS_MESSAGE_GLBOBSRCVREQUEST_H
