// Generated by gencpp from file usv_msgs/GlbObsRcvResponse.msg
// DO NOT EDIT!


#ifndef USV_MSGS_MESSAGE_GLBOBSRCVRESPONSE_H
#define USV_MSGS_MESSAGE_GLBOBSRCVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace usv_msgs
{
template <class ContainerAllocator>
struct GlbObsRcvResponse_
{
  typedef GlbObsRcvResponse_<ContainerAllocator> Type;

  GlbObsRcvResponse_()
    : result(false)  {
    }
  GlbObsRcvResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GlbObsRcvResponse_

typedef ::usv_msgs::GlbObsRcvResponse_<std::allocator<void> > GlbObsRcvResponse;

typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvResponse > GlbObsRcvResponsePtr;
typedef boost::shared_ptr< ::usv_msgs::GlbObsRcvResponse const> GlbObsRcvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator1> & lhs, const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator1> & lhs, const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msgs/GlbObsRcvResponse";
  }

  static const char* value(const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
;
  }

  static const char* value(const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GlbObsRcvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msgs::GlbObsRcvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSGS_MESSAGE_GLBOBSRCVRESPONSE_H
