// Generated by gencpp from file usv_msgs/GlbObsRcv.msg
// DO NOT EDIT!


#ifndef USV_MSGS_MESSAGE_GLBOBSRCV_H
#define USV_MSGS_MESSAGE_GLBOBSRCV_H

#include <ros/service_traits.h>


#include <usv_msgs/GlbObsRcvRequest.h>
#include <usv_msgs/GlbObsRcvResponse.h>


namespace usv_msgs
{

struct GlbObsRcv
{

typedef GlbObsRcvRequest Request;
typedef GlbObsRcvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlbObsRcv
} // namespace usv_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::usv_msgs::GlbObsRcv > {
  static const char* value()
  {
    return "7f352b44c251978f0843cd60887550cf";
  }

  static const char* value(const ::usv_msgs::GlbObsRcv&) { return value(); }
};

template<>
struct DataType< ::usv_msgs::GlbObsRcv > {
  static const char* value()
  {
    return "usv_msgs/GlbObsRcv";
  }

  static const char* value(const ::usv_msgs::GlbObsRcv&) { return value(); }
};


// service_traits::MD5Sum< ::usv_msgs::GlbObsRcvRequest> should match
// service_traits::MD5Sum< ::usv_msgs::GlbObsRcv >
template<>
struct MD5Sum< ::usv_msgs::GlbObsRcvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::usv_msgs::GlbObsRcv >::value();
  }
  static const char* value(const ::usv_msgs::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::usv_msgs::GlbObsRcvRequest> should match
// service_traits::DataType< ::usv_msgs::GlbObsRcv >
template<>
struct DataType< ::usv_msgs::GlbObsRcvRequest>
{
  static const char* value()
  {
    return DataType< ::usv_msgs::GlbObsRcv >::value();
  }
  static const char* value(const ::usv_msgs::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::usv_msgs::GlbObsRcvResponse> should match
// service_traits::MD5Sum< ::usv_msgs::GlbObsRcv >
template<>
struct MD5Sum< ::usv_msgs::GlbObsRcvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::usv_msgs::GlbObsRcv >::value();
  }
  static const char* value(const ::usv_msgs::GlbObsRcvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::usv_msgs::GlbObsRcvResponse> should match
// service_traits::DataType< ::usv_msgs::GlbObsRcv >
template<>
struct DataType< ::usv_msgs::GlbObsRcvResponse>
{
  static const char* value()
  {
    return DataType< ::usv_msgs::GlbObsRcv >::value();
  }
  static const char* value(const ::usv_msgs::GlbObsRcvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // USV_MSGS_MESSAGE_GLBOBSRCV_H
