// Generated by gencpp from file usv_msgs/ThrustCommand.msg
// DO NOT EDIT!


#ifndef USV_MSGS_MESSAGE_THRUSTCOMMAND_H
#define USV_MSGS_MESSAGE_THRUSTCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace usv_msgs
{
template <class ContainerAllocator>
struct ThrustCommand_
{
  typedef ThrustCommand_<ContainerAllocator> Type;

  ThrustCommand_()
    : header()
    , left_thrust_cmd(0.0)
    , right_thrust_cmd(0.0)  {
    }
  ThrustCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_thrust_cmd(0.0)
    , right_thrust_cmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_thrust_cmd_type;
  _left_thrust_cmd_type left_thrust_cmd;

   typedef double _right_thrust_cmd_type;
  _right_thrust_cmd_type right_thrust_cmd;





  typedef boost::shared_ptr< ::usv_msgs::ThrustCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usv_msgs::ThrustCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustCommand_

typedef ::usv_msgs::ThrustCommand_<std::allocator<void> > ThrustCommand;

typedef boost::shared_ptr< ::usv_msgs::ThrustCommand > ThrustCommandPtr;
typedef boost::shared_ptr< ::usv_msgs::ThrustCommand const> ThrustCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usv_msgs::ThrustCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usv_msgs::ThrustCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::usv_msgs::ThrustCommand_<ContainerAllocator1> & lhs, const ::usv_msgs::ThrustCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_thrust_cmd == rhs.left_thrust_cmd &&
    lhs.right_thrust_cmd == rhs.right_thrust_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::usv_msgs::ThrustCommand_<ContainerAllocator1> & lhs, const ::usv_msgs::ThrustCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace usv_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usv_msgs::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usv_msgs::ThrustCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usv_msgs::ThrustCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff278815bb5e6204701ce178b988e627";
  }

  static const char* value(const ::usv_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff278815bb5e6204ULL;
  static const uint64_t static_value2 = 0x701ce178b988e627ULL;
};

template<class ContainerAllocator>
struct DataType< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usv_msgs/ThrustCommand";
  }

  static const char* value(const ::usv_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 left_thrust_cmd #[-1,1]\n"
"float64 right_thrust_cmd\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::usv_msgs::ThrustCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_thrust_cmd);
      stream.next(m.right_thrust_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usv_msgs::ThrustCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usv_msgs::ThrustCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_thrust_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.left_thrust_cmd);
    s << indent << "right_thrust_cmd: ";
    Printer<double>::stream(s, indent + "  ", v.right_thrust_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USV_MSGS_MESSAGE_THRUSTCOMMAND_H
